### ISSUE TITLE
Please mark this project as broken

### ISSUE THREAD

**Issue by marcinant** [nlamirault/emacs-gitlab#3]
It simple doesn't work at all.
Important parts of code are commented out and it's impossible to connect to server.

**Comment by thomasf** [comment]
It is possible to connect but yes, last time i checked there were bugs and shortcomings all around.

**Comment by marcinant** [comment]
It is possible to connect but it's not possible to authorize and get results.

**Comment by thomasf** [comment]
Set the  gitlab-token-id instead of the username/password.  The larger problem is that emacs-gitlab does not or did not support fetching anything beyond result page #1.. I've been meaning to get involved to help fix that (that is why I'm watching this repo) but no time and so on...

**Comment by marcinant** [comment]
You are right I set up 'gitlab-token-id' and now I can list projects.... well kind of. Projects with empty descriptions are not on the list... 

I'll try to investigate this project and see if I can help to improve or fix documentation at least.
