### ISSUE TITLE
Feature request: Ivy support

### ISSUE THREAD

**Issue by manuel-uberti** [nlamirault/emacs-gitlab#33]
Hi,

is there any chance this package will support other completion mechanisms? In particular, I'm talking about [Ivy](https://github.com/abo-abo/swiper#ivy).

Just asking. :)

**Comment by nlamirault** [comment]
Sure :) I'm a big fan of ivy ...

**Comment by manuel-uberti** [comment]
Great! Can't wait for it. :)
