### ISSUE TITLE
open to PR adding functionality?

### ISSUE THREAD

**Issue by bryanwb** [nlamirault/emacs-gitlab#35]
hi, i have an emacs package that i would like to merge into emacs-gitlab.

https://github.com/bryanwb/emacs-glop provides a function to open the file at point in gitlab or to copy the url to the kill-ring. This is a bit different than the functionality that emacs-gitlab currently provides. Would you be open to a PR that adds this additional functionality?

**Comment by nlamirault** [comment]
Yes !

**Comment by bryanwb** [comment]
excellent, i'll start work on it. I am a newb at elisp, but i'll do my best to respect the conventions you use.

**Comment by bryanwb** [comment]
tks for quick feedback! closing
